package apollo.analysis;

import apollo.datamodel.CurationSet;
import apollo.datamodel.Sequence;
import apollo.datamodel.StrandedFeatureSet;
import junit.framework.TestCase;

public class RemoteBlastNCBITest extends TestCase {

  public void testRunAnalysis() throws Exception
  {
    String id = "test";
    String residues = "TTCAGAGTTAAGGAACTGTATTAATCGTGTAATTTCTGCTACGAATCCGCCCATTTGTATTTAGTGTGCT" +
    		"TCATGTACTATCATTCTCCTAAATTGGTTTTTTGAGTGGTTATTAATCTGCTTTGCAGTCAGGAGGAATC" +
    		"ATCTAAGTCAGTATGGACCAGAAGAAGAGGAAGTTGGAAGATCCACCAGCCACGAATGCGAAAGAAGACA" +
    		"ACACTGCTGTAGTTGGGGGACCAACAGTGTCTGTTCCTTCTTTCGTGATCACTAAGGAGGATGTCAAGAA" +
    		"GCTTTTGGAGTCATTTACGAAGGATCGATTGATGGATTTATTGGAAAATGCTGCTCTTGTTCATACAGGT" +
    		"TATTCCTCGTCGAGTTATCTATCGTCCTAAAGCTCATTTTGGATGTGGTTTTTCAACGCGAGAGATACAG" +
    		"TGATGGGTTTATATATTTTCATGTACTGTTCAACTTATTCACATGTTCTCGATGGGTGTCGCTGTTTGAC" +
    		"TTTTGCAGATGTTCTTCAGGAAATTCGCAAGGTGGCTGACAAAGTTCCTGGTCATCGGAAGATTTTTGTA" +
    		"AGGGGCCTTGGTTGGGACTCAACGACAGAAACCTTGAAGACAGTATTCTCACAATTTGGAGAAGTGGAGG" +
    		"AGGGGGCGGTTGTTATGGACAAGGGTACTGGAAAGAGTAGAGGCTTTGGATTTGTGACATTCATACACAT" +
    		"GGACGGTGCTCAACGATCACTGAAGGAACCTAGCAAGCGGATTGATGGACGGATGACAGATTGTCAGTTG" +
    		"GCATCAACTGGGGCGTTGCAAATAAATCCTAATCAAGAAGTTTCAACGAGAAAAATTTACGTGGGCAACA" +
    		"TATCCCTTGATCTTTCTGCGGACAGGCTGCTGGCTTTTTTCGCAGGATATGGAGAAATTGGAGAGGGTCC" +
    		"CTTAGGATTCGACAAATTCACTGGACGCTCACGAGGTTTCGCTTTGTTTATTTACAAGACAGTTGAAGCT" +
    		"ACAAAGAGGGCATTGTTGGAGCCAATCAAGACTTTAGATGGTATTCAAATGTACTGTAAGCTTGCCTCTG" +
    		"AGAATCAGAAACAGGGGCAGGGGAGGCAAGGCCCTCCCGGTAAAAGCGACAATGATTTAATACTAGGCAG" +
    		"GCAGCAGGTAATCTACATCAATCATCTTGTCCATCTGAAAATGCGTTTATTCTTATGGTCGGGGACCAGT" +
    		"TTGTATTTTAAAGCTGATGTGGTGTTCATTTGATCACATGTTTTTACGAAGTGGTACTGAGAGTAGTTGT" +
    		"TGTGAGAACCTTCTGCTGGCTTTTCTTGTGTGCAGATATCAACTCCTCCGTCCCTCTCAAACGAACAAAA" +
    		"TATGTCGTACGGATCCATGAATACTGGTTCATTAACTACTGGAATTCCGCTCAACCAGGGCGTGAATCAA" +
    		"GGAATGAGTCAAGGAAGTCACATGGGTCTCAATAATCATAATCAAGGTCTTAGCAACCTGAAGAGCACAT" +
    		"TGAACTCGCCCCTCAACTATACATTGAATTCATCATTATCTCCTCTAGGACAGTTAACGAATTCATCGTT" +
    		"AAATGGTTCTTTTAACTCCGGTCACCCACAAACATCCCTTGGAATGGGATCTTACAGTTCACAATTGGCT" +
    		"GTGTCCCAATATGGAGGTCAACCAACTGGCCTTGGTGGGCAACCTACATATTCTTCGATGAATGGGGTTC" +
    		"TTTATTGCTCGGCAGCCAACTCAGCAGCCTCGCAGCAGGTATTTAAAACGAATTTTATATTGCGCATGAC" +
    		"GATTTAGTGTAGGTCCTGTAATTTGCATGCTTAACTGTCTATTTTAATTAATTACATTACATCTAATGAG" +
    		"TGAGGCCGTTCGTATTATTCGGGATAACTGTGTTGATCTTGGCGGACCTGCAGTTTGTACCGAAGTACTT" +
    		"GACGTTGCATTCGCCTAATACTATGTCCAACACATGTATATTTAAAATCTGACTTCTCTCATCTACTGTA" +
    		"TATTTCTCAGCAAGCAGCGCTGCAGGTAGCTGGTGGTCATTACGGATATGGGTCATATCAAAGTCCTCAA" +
    		"CTTCCAACATCTTCTGCTCCTCGCGCCCCTCCCGTAGGAAATATGTACATGCCTTCCAACCATAACCTAA" +
    		"AAGGTAAGCATTGGTGTCTTCACTTTCTTGCTCTTTAAGGTGCGCTATTCTTTTACTGACCAATTGTGAG" +
    		"ACCTCCTAATTAAATATGCTCGAATGATTGTCCTCTTTTCGTTCAAAGTTGCGAGTTTGGTTCACGTCTG" +
    		"AGAGAGGCATCGGAGTTTTGAATGAATATTAAATCTTGGATGTTTTATTTTGGATGTTGAATACAAATTC" +
    		"AGCAATAACAATTTTTTTGTCTGTGATGTTTCATGTCTGGATTATCTACATGTCTGTGATCACTGTTCAG" +
    		"TGTATACAAGAGTTTCAGTTGTTTTCAATTAGGATGATTATGTTTGTGCTACATTGGGCAACAGAGGTTA" +
    		"TTTGTGAGAAGGGAGATTTAAGTACTAAACATTGTGCTTACTGTAAATGTTCTGTTGCGGATTTTGTTCT" +
    		"TTTGACTTTTTCTTTTTTTCTTTTTTTCTTTTCTCCAGTTCTTTGCAAATTGTGATAGTTTAACCTTTTT" +
    		"ATCTTAATAATGTTGCAAGCTTGTTGGTCTAGTTTCTTTGAGGAATTCAAGTTTCGAACGGGATATTACC" +
    		"ACAGTTTGATAGCAAATACAAAAAACAAGAGTTGAAATTAGTGGTGAAAAAGTTTGGTCATTTCATAACC" +
    		"GATGCCCATAATTTGAATCTCTGTGACTCTGAAAATCTCTAATATTTATCGTTTTTATCCATCAACTCTA" +
    		"GCGTACGCCATGCACTACTTATTGTTCTAGTAATTGACGGATCTCTGTTGACAATGTTGGTGGACATGGG" +
    		"ATTACCATGAGATAAGTTCCAGGCCCGATCGACCAGGTTTCACAAAGAAGCTTTAAAGATTATTTTTTCT" +
    		"TATCAAATTTAATGTATAAAGATCCAAAGTGGTTTATTGCCATGTTTTCAGTCAAGTAATTTCATGACTG" +
    		"AAAAGTTATGGAGACTAATTATTCCTTTTAATTGTA";
    CurationSet cs = new CurationSet();
    cs.setResults(new StrandedFeatureSet());
    Sequence seq = new Sequence(id, residues);
    cs.setRefSequence(seq);
    RemoteBlastNCBI blast = new RemoteBlastNCBI(RemoteBlastNCBI.BlastType.blastn, null);
    blast.runAnalysis(cs, seq, 1, 1);
  }
  
}
